version: '3.8'


services:
    mysql:
        image: mysql:8.3
        restart: always
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=laravel
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql

    adminer:
        image: adminer:4.8.1
        restart: always
        ports:
            - '8080:8080'
        depends_on:
            - mysql

    rabbitmq:
        image: rabbitmq:3.12.10-management
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
        ports:
            - '${RABBITMQ_PORT}:5672'
            - '${RABBITMQ_INTERFACE_PORT}:15672'


volumes:
    mysql_data:
